cookie:
  expiry_days: 30
  key: some_signature_key
  name: video_transcription_cookie
  path: /
credentials:
  usernames:
    someuser:
      email: someuser@example.com
      name: Some User
      password: $2b$12$P4JKVb2/8q8N4q8N4q8N4u
preauthorized:
  emails:
  - tutor@example.com
